CREATE DATABASE IF NOT EXISTS DB_SERVICO_HR;

USE DB_SERVICO_HR;

CREATE TABLE IF NOT EXISTS TB_FUNCIONARIOS(
ID BIGINT AUTO_INCREMENT,
NOME CHAR(255) NOT NULL,
NASCIMENTO INT,
SALARIO DECIMAL,
CARGO CHAR(255),
primary key (id)
);

SELECT * FROM TB_FUNCIONARIOS;

INSERT INTO TB_FUNCIONARIOS(NOME, NASCIMENTO, SALARIO, CARGO) VALUE("João", 26, 4000.00, "desenvolvedor");